name: Bookings_Local
version: '3.9'

services:
  frontend:
    build: ./frontend
    ports: "3000:3000"
    depends_on: 
      - backend

  backend:
    build: ./backend
    environment: 
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports: "8080:8080"
    depends_on:
      - redis
      

  redis:
    image: redis:alpine
    ports: "6379:6379"
